language: python
matrix:
  include:
      - python: 3.7
        dist: xenial
        sudo: true
      - python: 3.6
      - python: 3.5
notifications:
  email: false
install: pip install tox-travis
script: tox
